### ISSUE TITLE
The enviroment not work

### ISSUE THREAD

**Issue by yvquanli** [lich-uct/nonpher#3]
They are not work

    conda create -n nonpher -c conda-forge -c rdkit -c lich nonpher rdkit=2018.3.1 molpher-lib=0.0.0b2 libboost=1.65.1
    conda create -n nonpher -c conda-forge -c rdkit -c lich nonpher rdkit molpher-lib

**Comment by yvquanli** [comment]
/libmolpher.so.0.0: undefined symbol: _ZNK5RDKit4Atom9getSymbolB5cxx11Ev

ModuleNotFoundError: No module named '_core'

**Comment by martin-sicho** [comment]
Sorry for the late reply. I missed this. I think there is probably a mismatch with rdkit version. You could try to use the latest version of molpher-lib instead and see if correct dependencies get pulled with that one.

**Comment by yvquanli** [comment]
OK
